# Generated by Django 4.2.3 on 2023-08-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0002_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
